[package]
name = "syl-scr-common"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Creative-Difficulty"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.3.6", features = ["postgres", "chrono"] }
pgvector = { version = "0.4.1", features = ["diesel"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
