-- ============================================================================
-- YOUTUBE TABLES
-- Depends on: scores
-- ============================================================================

CREATE TABLE youtube_channels (
  -- The Youtube channel ID (generated by yt)
  channel_id text PRIMARY KEY,
  display_name text NOT NULL,
  username text NOT NULL,
  -- Some people fill this in for some reasonso  why not record it in the db
  bio_location text,

  vestibule_user_id text REFERENCES vestibule_users(id),

  bio text,
  
  -- Reference to downloaded profile picture (for visual similarity matching to discord pfps)
  profile_picture_asset_id uuid REFERENCES media_assets(id),

  -- For finding similar users in Discord accounts and across other platforms, TODO choose universal vector dimensions amount and choose embedding model (preferably selfhostable)
  name_embedding vector
);

CREATE TABLE youtube_videos (
  -- The part after youtube.com/watch?v=
  video_id text PRIMARY KEY,

  channel_id text NOT NULL REFERENCES youtube_channels(channel_id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  published_at timestamptz NOT NULL,
  total_views bigint NOT NULL DEFAULT 0,
  total_likes bigint NOT NULL DEFAULT 0,
  total_comments bigint NOT NULL DEFAULT 0,
  
  -- Content Details
  duration_seconds integer NOT NULL,
  broadcast_status text NOT NULL, -- Values: 'video', 'current_live', 'past_live', 'upcoming', 'none'
  
  -- Media & Discovery
  thumbnail_asset_id uuid REFERENCES media_assets(id),
  keyword_tags text[],

  added_at timestamptz DEFAULT NOW
);

CREATE TABLE youtube_comments (
  comment_id text PRIMARY KEY,
  video_id text NOT NULL REFERENCES youtube_videos(video_id) ON DELETE CASCADE,
  
  -- The channel that posted the comment
  author_raw_channel_id text NOT NULL,
  -- If the channel is already in the db, populate this field too
  author_channel_id text REFERENCES youtube_channels(channel_id) ON DELETE CASCADE,

  content text NOT NULL,
  
  like_count integer NOT NULL,
  
  published_at timestamptz NOT NULL,
  updated_at timestamptz,
  
  -- Self-reference for replies
  in_reply_to text REFERENCES youtube_comments(comment_id),
  
  -- Personality and pipeline metadata (mirroring messages table)
  score_id uuid REFERENCES scores(id),
  
  triage_status text NOT NULL DEFAULT 'pending',
  is_significant boolean NOT NULL,
  skill_status text,
  personality_status text,
  processed_at timestamptz
);
