-- Your SQL goes here
REVOKE ALL PRIVILEGES ON SCHEMA public FROM "krauzekrap";

GRANT USAGE ON SCHEMA public TO "krauzekrap";

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "krauzekrap";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "krauzekrap";
